const thephrases = [

"Not in kansas anymore",
"off with his head",
"Famous last words",
"female of the species",
"alive and kicking",
"all you can eat",
"busy as a bee",
"easy as pie",
"fit as a fiddle",
"back to basics",
"break a leg",
"the buck stops here",
"dollars to donuts",
"fair and square",
"sunny side up",
"flavor of the month",
"head over heels",
"hot off the press",
"if the shoe fits",
"all greek to me",
"jack of all trades",
"amber waves of grain",
"not rocket science",
"jump the gun",
"kiss and tell",
"knock on wood",
"less is more",
"live long and prosper",
"love is blind",
"mumbo jumbo",
"nip and tuck",
"off the record",
"on cloud nine",
"one stop shop",
"play it again Sam",
"point and click",
"quid pro quo",
"the real McCoy",
"rock and roll",
"saved by the bell",
"shot in the dark",
"smoke and mirrors",
"talk to the hand",
"apple of my eye",
"the bees knees",
"the last straw",
"thick and thin",
"outside the box",
"tying the knot",
"touch and go",
"upside down",
"vicious circle",
"whistle blower",

];
